// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies;

public enum Status
{
	_200_OK(new java.lang.String[][] { new java.lang.String[] { "en_US", "OK" } }),
	_201_Created(new java.lang.String[][] { new java.lang.String[] { "en_US", "Created" } }),
	_202_Accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Accepted" } }),
	_204_No_Content(new java.lang.String[][] { new java.lang.String[] { "en_US", "No Content" } }),
	_400_Bad_Request(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bad Request" } }),
	_401_Unauthorized(new java.lang.String[][] { new java.lang.String[] { "en_US", "Unauthorized" } }),
	_403_Forbidden(new java.lang.String[][] { new java.lang.String[] { "en_US", "Forbidden" } }),
	_404_Not_Found(new java.lang.String[][] { new java.lang.String[] { "en_US", "Not Found" } }),
	_405_Method_Not_Allowed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Method Not Allowed" } }),
	_406_Not_Acceptable(new java.lang.String[][] { new java.lang.String[] { "en_US", "Not Acceptable" } }),
	_409_Conflict(new java.lang.String[][] { new java.lang.String[] { "en_US", "Conflict" } }),
	_410_Gone(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gone" } }),
	_429_Rate_Limit_Exceeded(new java.lang.String[][] { new java.lang.String[] { "en_US", "Rate Limit Exceeded" } }),
	_500_Internal_Server_Error(new java.lang.String[][] { new java.lang.String[] { "en_US", "Internal Server Error" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Status(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
