// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import rest_responses.ErrorMessageProvider;
import rest_responses.RESTResponseProvider;
import java.util.UUID;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The request could not be completed due to a conflict with the current state of the resource. 
 * This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request. 
 * 
 * The response body SHOULD include enough information for the user to recognize the source of the conflict. Ideally, the response entity would include enough information for the user or user agent to fix the problem; however, that might not be possible and is not required.
 */
public class Create_422_UNPROCESSABLE_CONTENT extends UserAction<IMendixObject>
{
	/** @deprecated use HTTPResponse.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HTTPResponse;
	private final system.proxies.HttpResponse HTTPResponse;
	private final java.lang.String Detail;
	private final java.lang.String LogMessageDetails;

	public Create_422_UNPROCESSABLE_CONTENT(
		IContext context,
		IMendixObject _hTTPResponse,
		java.lang.String _detail,
		java.lang.String _logMessageDetails
	)
	{
		super(context);
		this.__HTTPResponse = _hTTPResponse;
		this.HTTPResponse = _hTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), _hTTPResponse);
		this.Detail = _detail;
		this.LogMessageDetails = _logMessageDetails;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ErrorMessageProvider emp = new ErrorMessageProvider(getContext(), "Unprocessable Content", this.Detail, 422, null, null, LogMessageDetails);
		
		RESTResponseProvider rp = new RESTResponseProvider(this.getContext(), this.HTTPResponse, 422, emp.getJSONResponseMessage(), "Unprocessable Content");
		return rp.getResponse();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_422_UNPROCESSABLE_CONTENT";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
