// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import javax.servlet.http.HttpServletRequest;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import rest_responses.ErrorMessageProvider;
import rest_responses.RESTResponseProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returned when a request cannot be served due to the application its rate limit having been exhausted for the resource.
 */
public class Create_429_TOO_MANY_REQUESTS extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __HTTPResponse;
	private system.proxies.HttpResponse HTTPResponse;
	private java.lang.String Detail;
	private java.lang.String RetryAfter;
	private java.lang.String LogMessageDetails;

	public Create_429_TOO_MANY_REQUESTS(IContext context, IMendixObject HTTPResponse, java.lang.String Detail, java.lang.String RetryAfter, java.lang.String LogMessageDetails)
	{
		super(context);
		this.__HTTPResponse = HTTPResponse;
		this.Detail = Detail;
		this.RetryAfter = RetryAfter;
		this.LogMessageDetails = LogMessageDetails;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.HTTPResponse = this.__HTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), __HTTPResponse);

		// BEGIN USER CODE
		HttpServletRequest servlet = this.getContext().getRuntimeRequest().get().getHttpServletRequest();
		
		ErrorMessageProvider emp = new ErrorMessageProvider(getContext(), "Too Many Requests", servlet.getMethod() + " " + servlet.getPathInfo(), 429, null, null, LogMessageDetails);

		RESTResponseProvider rp = new RESTResponseProvider(this.context(), __HTTPResponse, 429, emp.getJSONResponseMessage(), "Too Many Requests");

		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_429_TOO_MANY_REQUESTS";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
