// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import javax.servlet.http.HttpServletRequest;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import rest_responses.ErrorMessageProvider;
import rest_responses.RESTResponseProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Returned when a request cannot be served due to the application its rate limit having been exhausted for the resource.
 */
public class Create_429_TOO_MANY_REQUESTS extends UserAction<IMendixObject>
{
	/** @deprecated use HTTPResponse.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HTTPResponse;
	private final system.proxies.HttpResponse HTTPResponse;
	private final java.lang.String Detail;
	private final java.lang.String RetryAfter;
	private final java.lang.String LogMessageDetails;

	public Create_429_TOO_MANY_REQUESTS(
		IContext context,
		IMendixObject _hTTPResponse,
		java.lang.String _detail,
		java.lang.String _retryAfter,
		java.lang.String _logMessageDetails
	)
	{
		super(context);
		this.__HTTPResponse = _hTTPResponse;
		this.HTTPResponse = _hTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), _hTTPResponse);
		this.Detail = _detail;
		this.RetryAfter = _retryAfter;
		this.LogMessageDetails = _logMessageDetails;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		HttpServletRequest servlet = this.getContext().getRuntimeRequest().get().getHttpServletRequest();
		
		ErrorMessageProvider emp = new ErrorMessageProvider(getContext(), "Too Many Requests", servlet.getMethod() + " " + servlet.getPathInfo(), 429, null, null, LogMessageDetails);

		RESTResponseProvider rp = new RESTResponseProvider(this.getContext(), this.HTTPResponse, 429, emp.getJSONResponseMessage(), "Too Many Requests");

		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_429_TOO_MANY_REQUESTS";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
