// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import rest_responses.RESTResponseProvider;

/**
 * A Multi-Status response conveys information about multiple resources in situations where multiple status codes might be appropriate.
 */
public class Create_207_MULTI_STATUS extends UserAction<IMendixObject>
{
	/** @deprecated use HTTPResponse.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HTTPResponse;
	private final system.proxies.HttpResponse HTTPResponse;
	private final java.lang.String Content;
	private final java.lang.String ContentType;

	public Create_207_MULTI_STATUS(
		IContext context,
		IMendixObject _hTTPResponse,
		java.lang.String _content,
		java.lang.String _contentType
	)
	{
		super(context);
		this.__HTTPResponse = _hTTPResponse;
		this.HTTPResponse = _hTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), _hTTPResponse);
		this.Content = _content;
		this.ContentType = _contentType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		RESTResponseProvider rp = new RESTResponseProvider(this.getContext(), this.HTTPResponse,  207, this.Content, "MULTI-STATUS");

		rp.setOrOverrideHttpHeader("Content-type", this.ContentType);
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_207_MULTI_STATUS";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
