// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import rest_responses.RESTResponseProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The request has been fulfilled and resulted in a new resource being created..
 */
public class Create_201_CREATED extends UserAction<IMendixObject>
{
	/** @deprecated use HTTPResponse.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HTTPResponse;
	private final system.proxies.HttpResponse HTTPResponse;
	private final java.lang.String Content;
	private final java.lang.String Location;

	public Create_201_CREATED(
		IContext context,
		IMendixObject _hTTPResponse,
		java.lang.String _content,
		java.lang.String _location
	)
	{
		super(context);
		this.__HTTPResponse = _hTTPResponse;
		this.HTTPResponse = _hTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), _hTTPResponse);
		this.Content = _content;
		this.Location = _location;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		RESTResponseProvider rp = new RESTResponseProvider(this.getContext(), HTTPResponse, 201, this.Content, "Created");
		
		if( Location != null && "" != Location) {
			rp.setOrOverrideHttpHeader("Location", this.Location);
		}
		
		return rp.getResponse();		
		

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_201_CREATED";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
