// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import rest_responses.ErrorMessageProvider;
import rest_responses.RESTResponseProvider;
import java.util.UUID;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The authentication credentials are missing, or if supplied are not valid or not sufficient to access the resource.
 */
public class Create_401_UNAUTHORIZED extends UserAction<IMendixObject>
{
	private final java.lang.String WWWAuthenticate;
	/** @deprecated use HTTPResponse.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HTTPResponse;
	private final system.proxies.HttpResponse HTTPResponse;
	private final java.lang.String Details;
	private final java.lang.String LogMessageDetails;

	public Create_401_UNAUTHORIZED(
		IContext context,
		java.lang.String _wWWAuthenticate,
		IMendixObject _hTTPResponse,
		java.lang.String _details,
		java.lang.String _logMessageDetails
	)
	{
		super(context);
		this.WWWAuthenticate = _wWWAuthenticate;
		this.__HTTPResponse = _hTTPResponse;
		this.HTTPResponse = _hTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), _hTTPResponse);
		this.Details = _details;
		this.LogMessageDetails = _logMessageDetails;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		Integer status = 401;
		ErrorMessageProvider emp = new ErrorMessageProvider(getContext(), "Unauthorized", 
				this.Details, status, null, null, LogMessageDetails);
		
		
		RESTResponseProvider rp = new RESTResponseProvider(this.getContext(), HTTPResponse, status, emp.getJSONResponseMessage(), "Unauthorized");
		rp.addHttpHeader("WWW-Authenticate", this.WWWAuthenticate);
		
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_401_UNAUTHORIZED";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
