// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import rest_responses.ErrorMessageProvider;
import rest_responses.RESTResponseProvider;
import java.util.UUID;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The request could not be understood by the server due to malformed syntax.
 */
public class Create_500_INTERNAL_SERVER_ERROR extends UserAction<IMendixObject>
{
	private final java.lang.String Content;
	/** @deprecated use HTTPResponse.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HTTPResponse;
	private final system.proxies.HttpResponse HTTPResponse;
	private final java.lang.String LogMessage;

	public Create_500_INTERNAL_SERVER_ERROR(
		IContext context,
		java.lang.String _content,
		IMendixObject _hTTPResponse,
		java.lang.String _logMessage
	)
	{
		super(context);
		this.Content = _content;
		this.__HTTPResponse = _hTTPResponse;
		this.HTTPResponse = _hTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), _hTTPResponse);
		this.LogMessage = _logMessage;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		ErrorMessageProvider emp = new ErrorMessageProvider(getContext(), "Internal Server Error",  this.Content, 500, null, null, LogMessage);

		RESTResponseProvider rp = new RESTResponseProvider(this.getContext(), HTTPResponse, 500, emp.getJSONResponseMessage(), "Internal Server Error");
	
		Core.getLogger("ProblemJSONModule").error(emp.getJSONResponseMessage());
		
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_500_INTERNAL_SERVER_ERROR";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
