// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import javax.servlet.http.HttpServletRequest;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import rest_responses.ErrorMessageProvider;
import rest_responses.RESTResponseProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.util.UUID;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The URI requested is invalid or the resource requested does not exists.
 */
public class Create_404_NOT_FOUND extends UserAction<IMendixObject>
{
	/** @deprecated use HTTPResponse.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HTTPResponse;
	private final system.proxies.HttpResponse HTTPResponse;
	private final java.lang.String LogMessageDetails;

	public Create_404_NOT_FOUND(
		IContext context,
		IMendixObject _hTTPResponse,
		java.lang.String _logMessageDetails
	)
	{
		super(context);
		this.__HTTPResponse = _hTTPResponse;
		this.HTTPResponse = _hTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), _hTTPResponse);
		this.LogMessageDetails = _logMessageDetails;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		HttpServletRequest servlet = this.getContext().getRuntimeRequest().get().getHttpServletRequest();
		
		ErrorMessageProvider emp = new ErrorMessageProvider(getContext(), "Not Found", 
				servlet.getMethod() + " " + servlet.getPathInfo(), 404, null, null, LogMessageDetails);
		
		RESTResponseProvider rp = new RESTResponseProvider(this.getContext(), this.HTTPResponse, 404, emp.getJSONResponseMessage(), "Not Found");
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_404_NOT_FOUND";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
