// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import rest_responses.RESTResponseProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The server successfully processed the request, but is not returning any content. E.G.Delete
 */
public class Create_204_NO_CONTENT extends UserAction<IMendixObject>
{
	/** @deprecated use HTTPResponse.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HTTPResponse;
	private final system.proxies.HttpResponse HTTPResponse;

	public Create_204_NO_CONTENT(
		IContext context,
		IMendixObject _hTTPResponse
	)
	{
		super(context);
		this.__HTTPResponse = _hTTPResponse;
		this.HTTPResponse = _hTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), _hTTPResponse);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		RESTResponseProvider rp = new RESTResponseProvider(this.getContext(),this.HTTPResponse, 204, "", "No Content");
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_204_NO_CONTENT";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
