// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import javax.servlet.http.HttpServletRequest;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import rest_responses.RESTResponseProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returned when a request cannot be served due to the application its rate limit having been exhausted for the resource.
 */
public class Create_429_TOO_MANY_REQUESTS extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __HTTPResponse;
	private system.proxies.HttpResponse HTTPResponse;

	public Create_429_TOO_MANY_REQUESTS(IContext context, IMendixObject HTTPResponse)
	{
		super(context);
		this.__HTTPResponse = HTTPResponse;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.HTTPResponse = __HTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), __HTTPResponse);

		// BEGIN USER CODE
		HttpServletRequest servlet = this.getContext().getRuntimeRequest().get().getHttpServletRequest();

		RESTResponseProvider rp = new RESTResponseProvider(this.context(), __HTTPResponse, 429, "", "Too Many Requests");
		Core.getLogger("ProblemJSONModule").error("429 Too Many Requests - " + servlet.getMethod() + " " + servlet.getPathInfo());
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_429_TOO_MANY_REQUESTS";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
