// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import rest_responses.RESTResponseProvider;
import java.util.UUID;

/**
 * The request could not be understood by the server due to malformed syntax.
 */
public class Create_400_BAD_REQUEST extends CustomJavaAction<IMendixObject>
{
	private java.lang.String Title;
	private IMendixObject __HTTPResponse;
	private system.proxies.HttpResponse HTTPResponse;
	private java.lang.String Detail;
	private java.lang.String TypeURI;
	private java.util.List<IMendixObject> __ValidationErrors;
	private java.util.List<rest_responses.proxies.ValidationError> ValidationErrors;

	public Create_400_BAD_REQUEST(IContext context, java.lang.String Title, IMendixObject HTTPResponse, java.lang.String Detail, java.lang.String TypeURI, java.util.List<IMendixObject> ValidationErrors)
	{
		super(context);
		this.Title = Title;
		this.__HTTPResponse = HTTPResponse;
		this.Detail = Detail;
		this.TypeURI = TypeURI;
		this.__ValidationErrors = ValidationErrors;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.HTTPResponse = __HTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), __HTTPResponse);

		this.ValidationErrors = new java.util.ArrayList<rest_responses.proxies.ValidationError>();
		if (__ValidationErrors != null)
			for (IMendixObject __ValidationErrorsElement : __ValidationErrors)
				this.ValidationErrors.add(rest_responses.proxies.ValidationError.initialize(getContext(), __ValidationErrorsElement));

		// BEGIN USER CODE
		String instance = UUID.randomUUID().toString();
		
		String jsonResult = rest_responses.proxies.microflows.Microflows.getProblemResponseAsJSON(getContext(), this.Title, this.Detail, Integer.toUnsignedLong(400), this.TypeURI,this.ValidationErrors, instance); 
		
		Core.getLogger("ProblemJSONModule").error("400 " + this.Title + " (instance:" + instance + ")");
		
		RESTResponseProvider rp = new RESTResponseProvider(this.context(), __HTTPResponse, 400, jsonResult, "Bad Request");
		
		rp.addHttpHeader("Content-type", "application/problem+json");
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_400_BAD_REQUEST";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
