// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import rest_responses.RESTResponseProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * A Multi-Status response conveys information about multiple resources in situations where multiple status codes might be appropriate.
 */
public class Create_207_MULTI_STATUS extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __HTTPResponse;
	private system.proxies.HttpResponse HTTPResponse;
	private java.lang.String Content;
	private java.lang.String ContentType;

	public Create_207_MULTI_STATUS(IContext context, IMendixObject HTTPResponse, java.lang.String Content, java.lang.String ContentType)
	{
		super(context);
		this.__HTTPResponse = HTTPResponse;
		this.Content = Content;
		this.ContentType = ContentType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.HTTPResponse = __HTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), __HTTPResponse);

		// BEGIN USER CODE
		
		RESTResponseProvider rp = new RESTResponseProvider(this.context(), __HTTPResponse,  207, this.Content, "MULTI-STATUS");
		
		if(this.ContentType == null || this.ContentType.isEmpty()) {
			this.ContentType = "application/json";
		}
		
		rp.addHttpHeader("Content-type", this.ContentType);
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_207_MULTI_STATUS";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
