// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import javax.servlet.http.HttpServletRequest;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import rest_responses.RESTResponseProvider;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.util.UUID;

/**
 * The URI requested is invalid or the resource requested does not exists.
 */
public class Create_404_NOT_FOUND extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __HTTPResponse;
	private system.proxies.HttpResponse HTTPResponse;

	public Create_404_NOT_FOUND(IContext context, IMendixObject HTTPResponse)
	{
		super(context);
		this.__HTTPResponse = HTTPResponse;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.HTTPResponse = __HTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), __HTTPResponse);

		// BEGIN USER CODE
		String instance = UUID.randomUUID().toString();
		HttpServletRequest servlet = this.getContext().getRuntimeRequest().get().getHttpServletRequest();
		
		String jsonResult = rest_responses.proxies.microflows.Microflows.getProblemResponseAsJSON(getContext(), "The resource wasn't found.", null, Integer.toUnsignedLong(404), null,null, instance); 
		
		Core.getLogger("ProblemJSONModule").warn("404 Resource not found - "+ servlet.getMethod() + " " + servlet.getPathInfo() + " (instance:" + instance + ")");
		
		RESTResponseProvider rp = new RESTResponseProvider(this.context(), __HTTPResponse, 404, jsonResult, "Not Found");
		rp.addHttpHeader("Content-type", "application/json");
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_404_NOT_FOUND";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
