// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rest_responses.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import rest_responses.ErrorMessageProvider;
import rest_responses.RESTResponseProvider;
import java.util.UUID;

/**
 * The authentication credentials are missing, or if supplied are not valid or not sufficient to access the resource.
 */
public class Create_401_UNAUTHORIZED extends CustomJavaAction<IMendixObject>
{
	private java.lang.String WWWAuthenticate;
	private IMendixObject __HTTPResponse;
	private system.proxies.HttpResponse HTTPResponse;
	private java.lang.String Details;
	private java.lang.String LogMessageDetails;

	public Create_401_UNAUTHORIZED(IContext context, java.lang.String WWWAuthenticate, IMendixObject HTTPResponse, java.lang.String Details, java.lang.String LogMessageDetails)
	{
		super(context);
		this.WWWAuthenticate = WWWAuthenticate;
		this.__HTTPResponse = HTTPResponse;
		this.Details = Details;
		this.LogMessageDetails = LogMessageDetails;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.HTTPResponse = this.__HTTPResponse == null ? null : system.proxies.HttpResponse.initialize(getContext(), __HTTPResponse);

		// BEGIN USER CODE
		Integer status = 401;
		ErrorMessageProvider emp = new ErrorMessageProvider(getContext(), "Unauthorized", 
				this.Details, status, null, null, LogMessageDetails);
		
		
		RESTResponseProvider rp = new RESTResponseProvider(this.context(), HTTPResponse.getMendixObject(), status, emp.getJSONResponseMessage(), "Unauthorized");
		rp.addHttpHeader("WWW-Authenticate", this.WWWAuthenticate);
		
		return rp.getResponse();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_401_UNAUTHORIZED";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
