// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rest_responses.proxies;

public class ErrorResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject errorResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "REST_Responses.ErrorResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_type("_type"),
		title("title"),
		detail("detail"),
		status("status"),
		instance("instance"),
		ErrorResponse_ValidationError("REST_Responses.ErrorResponse_ValidationError"),
		ErrorResponse_Root("REST_Responses.ErrorResponse_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ErrorResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "REST_Responses.ErrorResponse"));
	}

	protected ErrorResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject errorResponseMendixObject)
	{
		if (errorResponseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("REST_Responses.ErrorResponse", errorResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a REST_Responses.ErrorResponse");

		this.errorResponseMendixObject = errorResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ErrorResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rest_responses.proxies.ErrorResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rest_responses.proxies.ErrorResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rest_responses.proxies.ErrorResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rest_responses.proxies.ErrorResponse(context, mendixObject);
	}

	public static rest_responses.proxies.ErrorResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rest_responses.proxies.ErrorResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of title
	 */
	public final java.lang.String gettitle()
	{
		return gettitle(getContext());
	}

	/**
	 * @param context
	 * @return value of title
	 */
	public final java.lang.String gettitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.title.toString());
	}

	/**
	 * Set value of title
	 * @param title
	 */
	public final void settitle(java.lang.String title)
	{
		settitle(getContext(), title);
	}

	/**
	 * Set value of title
	 * @param context
	 * @param title
	 */
	public final void settitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.title.toString(), title);
	}

	/**
	 * @return value of detail
	 */
	public final java.lang.String getdetail()
	{
		return getdetail(getContext());
	}

	/**
	 * @param context
	 * @return value of detail
	 */
	public final java.lang.String getdetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.detail.toString());
	}

	/**
	 * Set value of detail
	 * @param detail
	 */
	public final void setdetail(java.lang.String detail)
	{
		setdetail(getContext(), detail);
	}

	/**
	 * Set value of detail
	 * @param context
	 * @param detail
	 */
	public final void setdetail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String detail)
	{
		getMendixObject().setValue(context, MemberNames.detail.toString(), detail);
	}

	/**
	 * @return value of status
	 */
	public final java.lang.Integer getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final java.lang.Integer getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.status.toString());
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(java.lang.Integer status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer status)
	{
		getMendixObject().setValue(context, MemberNames.status.toString(), status);
	}

	/**
	 * @return value of instance
	 */
	public final java.lang.String getinstance()
	{
		return getinstance(getContext());
	}

	/**
	 * @param context
	 * @return value of instance
	 */
	public final java.lang.String getinstance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.instance.toString());
	}

	/**
	 * Set value of instance
	 * @param instance
	 */
	public final void setinstance(java.lang.String instance)
	{
		setinstance(getContext(), instance);
	}

	/**
	 * Set value of instance
	 * @param context
	 * @param instance
	 */
	public final void setinstance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instance)
	{
		getMendixObject().setValue(context, MemberNames.instance.toString(), instance);
	}

	/**
	 * @return value of ErrorResponse_ValidationError
	 */
	public final java.util.List<rest_responses.proxies.ValidationError> getErrorResponse_ValidationError() throws com.mendix.core.CoreException
	{
		return getErrorResponse_ValidationError(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorResponse_ValidationError
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<rest_responses.proxies.ValidationError> getErrorResponse_ValidationError(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<rest_responses.proxies.ValidationError> result = new java.util.ArrayList<rest_responses.proxies.ValidationError>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ErrorResponse_ValidationError.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(rest_responses.proxies.ValidationError.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ErrorResponse_ValidationError
	 * @param errorresponse_validationerror
	 */
	public final void setErrorResponse_ValidationError(java.util.List<rest_responses.proxies.ValidationError> errorresponse_validationerror)
	{
		setErrorResponse_ValidationError(getContext(), errorresponse_validationerror);
	}

	/**
	 * Set value of ErrorResponse_ValidationError
	 * @param context
	 * @param errorresponse_validationerror
	 */
	public final void setErrorResponse_ValidationError(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<rest_responses.proxies.ValidationError> errorresponse_validationerror)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (rest_responses.proxies.ValidationError proxyObject : errorresponse_validationerror)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ErrorResponse_ValidationError.toString(), identifiers);
	}

	/**
	 * @return value of ErrorResponse_Root
	 */
	public final rest_responses.proxies.Root getErrorResponse_Root() throws com.mendix.core.CoreException
	{
		return getErrorResponse_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorResponse_Root
	 */
	public final rest_responses.proxies.Root getErrorResponse_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rest_responses.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ErrorResponse_Root.toString());
		if (identifier != null)
			result = rest_responses.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ErrorResponse_Root
	 * @param errorresponse_root
	 */
	public final void setErrorResponse_Root(rest_responses.proxies.Root errorresponse_root)
	{
		setErrorResponse_Root(getContext(), errorresponse_root);
	}

	/**
	 * Set value of ErrorResponse_Root
	 * @param context
	 * @param errorresponse_root
	 */
	public final void setErrorResponse_Root(com.mendix.systemwideinterfaces.core.IContext context, rest_responses.proxies.Root errorresponse_root)
	{
		if (errorresponse_root == null)
			getMendixObject().setValue(context, MemberNames.ErrorResponse_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ErrorResponse_Root.toString(), errorresponse_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return errorResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rest_responses.proxies.ErrorResponse that = (rest_responses.proxies.ErrorResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "REST_Responses.ErrorResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
