// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package test.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Test module
	public static test.proxies.Helper dS_Test(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Test.DS_Test").withParams(params).execute(context);
		return result == null ? null : test.proxies.Helper.initialize(context, result);
	}
	public static void getHTTPResponse(IContext context, test.proxies.Helper _helper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Helper", _helper == null ? null : _helper.getMendixObject());
		Core.microflowCall("Test.GetHTTPResponse").withParams(params).execute(context);
	}
	public static system.proxies.HttpResponse getHTTPResponseObject(IContext context, test.proxies.Helper _helper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Helper", _helper == null ? null : _helper.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Test.GetHTTPResponseObject").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
}