// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rest_responses.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the REST_Responses module

	public static boolean getEnableMendixErrorFormat()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("REST_Responses.EnableMendixErrorFormat");
	}
}